# -*- coding: utf-8 -*-
"""Week1Challenge-Day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uO1KNXbu_uWnd5ExtaP8adLOM8afFtUN

Apolo Barnabaas
Week1-Challenge_Day4

Challenge 1: Multiples of a Number

Q1. Ask the user for two inputs:

A number (integer).
A length (integer).
"""

number = int(input("Enter a number:"))
length = int (input("Enter the lenhth :"))

#Q2. Create a program that generates a list of multiples of the given number.

number = int(input("Enter a number: "))

count = int(input("How many multiples do you want? "))

multiples = []

for i in range(1, count + 1):
    multiples.append(number * i)

print("Multiples of", number, "are:", multiples)

#Q3 The list should stop when it reaches the length specified by the user.

number = int(input("Enter a number: "))
length = int(input("Enter desired list length: "))
multiples = []

i = 1
while len(multiples) < length:
    multiples.append(number * i)
    i += 1

# Output
print("Multiples:", multiples)

"""Challenge 2: Remove Consecutive Duplicate Letters

1. Ask the user for a string.**bold text**
2. Write a program that processes the string to remove consecutive duplicate letters.


"""

text = input("Enter a string: ")

result = ""
for char in text:
    if not result or char != result[-1]:
        result += char

print(result)